name: Bit Automation Pipeline

on:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REQUEST_PAYMENT_ENDPOINT: ${{ secrets.REQUEST_PAYMENT_ENDPOINT }}
      TRANSACTIONS_TABLE_NAME: ${{ secrets.TRANSACTIONS_TABLE_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run backend tests
        run: mvn clean test -Dgroups=backend
